apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          {{- $repo := .Values.image.repository -}}
          {{- if eq .Release.Name "catalog-service" -}}
          {{- $repo = "logipulse-catalog-service" -}}
          {{- else if eq .Release.Name "order-api" -}}
          {{- $repo = "logipulse-order-service" -}}
          {{- else if eq .Release.Name "fleet-service" -}}
          {{- $repo = "logipulse-fleet-service" -}}
          {{- else if eq .Release.Name "notification-service" -}}
          {{- $repo = "logipulse-notification-service" -}}
          {{- else if eq .Release.Name "frontend-ui" -}}
          {{- $repo = "logipulse-frontend-ui" -}}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readonlyRootFilesystem: true
          image: "{{ $repo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: logipulse-config
                  key: RABBITMQ_HOST
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: logipulse-secrets
                  key: jwt-secret
            - name: JwtSettings__Key
              valueFrom:
                secretKeyRef:
                  name: logipulse-secrets
                  key: jwt-secret
            {{- if or .Values.env.useSql .Values.env.sqlConnectionString }}
            - name: SQL_CONNECTIONSTRING
              {{- if .Values.env.sqlConnectionString }}
              value: {{ .Values.env.sqlConnectionString | quote }}
              {{- else }}
              value: "Server=sqlserver-service.logipulse.svc.cluster.local,1433;Database=LogiPulseOrders;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;"
              {{- end }}
            {{- end }}
          resources:
            requests:
              cpu: "100m"      # 100 millicores (0.1 CPU core baseline)
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
