apiVersion: v1
kind: ConfigMap
metadata:
  name: logipulse-config
  namespace: logipulse
data:
  AZURE_SERVICEBUS_HOST: "sb-logipulse-prod.servicebus.windows.net"
  SQL_SERVER_HOST: "sqlserver-service.logipulse.svc.cluster.local"
  SQL_DB_NAME: "LogiPulseOrders"
