apiVersion: v1
kind: ConfigMap
metadata:
  name: logipulse-config
  namespace: logipulse
data:
  RABBITMQ_HOST: "rabbitmq-service"
  SQL_SERVER_HOST: "sqlserver-service"
  SQL_DB_NAME: "LogiPulseOrders"
