apiVersion: v1
kind: Secret
metadata:
  name: logipulse-secrets
  namespace: logipulse
type: Opaque
data:
  sql-password: "WW91clN0cm9uZ0BQYXNzd29yZDEyMw=="
  jwt-secret: "WW91clN1cGVyU2VjcmV0S2V5VGhhdElzQXRMZWFzdDMyQ2hhcmFjdGVyc0xvbmch"
