apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
  namespace: logipulse
spec:
  serviceName: "sqlserver-service"
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
          name: mssql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "YourStrong@Password123"
        volumeMounts:
        - name: sqlserver-data
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: sqlserver-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "default" # Natively uses AKS's built-in managed Azure premium storage class
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: logipulse
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlserver